version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: _docker/Dockerfile.server
    image: ex4/server:latest
    ports:
      - "8081:8080"
  api:
    build:
      context: .
      dockerfile: _docker/Dockerfile.api
    image: ex4/api:latest
    ports:
      - "8080:8080"

